language: go
go:
- 1.8
cache:
  directories:
  - vendor
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
install:
- glide install
script:
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install --force
- gometalinter --vendor --fast --disable=gotype --disable=vetshadow --skip=mock ./...
- go test -race $(glide novendor)
after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email:
  - platform@serverless.com
env:
  global:
    secure: efeE2cEyODRrhqOWlplRFJ8lJxqfwn6CPmtdemqoyd8zP17oFqxwKOVRI0rV8JT6IiD4gE52WxJuQsFVVnvsCPyuLeBXcgoRAIUhTNuGafjeTCqcd74zksCeg/nHQ0KBCNJ65wnBPLEJzPS5Ame12Z+NqCc7lfFZmBUsixgHUjdpo+qlZJlA9C7FymVEwbBJXKUW6DtKgzgPLZi0aP/AjVwC5Ig1Ea7gqvtzVx+9kimQTXwgh9zIEgi3jrpRedWYL6354u57Lk1rtw/qLeuHvCch/6c3rlKmAdphv4UpA0w6urACLUBXRpL+A6J7t8vgyX6azcev7W5+jwX+CQVZgeor0VPJDxVKbkwB3yUklntZAFQOkB8VGjqHxEPSJA5wObgwDPK7guI3zozO9NJh/kzS8FdDFKymxfmfs0cK74JbIrXfevLASUekdRNBQWByWzZllAtHEOLegIyJmkGoWpMa6hePCBYwCDLkn0ax7ZjgnrWnBZ2Sqc+94vc+OX0siExxDHllNjiTDk9lWdzx2OL96G/bxSksLSrhi/vBG59q2khsDpR0pFf0feqfJ4UbDqCM7ikc20wFwrr2YZyRWtwJrubrcRZlmf4ZUDPAA7omyXHCwuFHLmQL/uqCTbucm9z9ZqqIBOyo+KsBPElaKSsnjSV+5Sl2gMWdbzTZC18=
