language: go
go:
- 1.8
cache:
  directories:
  - vendor
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
install:
- glide install
script:
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install --force
- gometalinter --vendor --fast --disable=gotype --disable=vetshadow --skip=mock ./...
- go test -race $(glide novendor)
after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email:
  - platform@serverless.com
env:
  global:
    secure: bqRQOT67Pg5r4a03xg9C2YeIhi8xqLxFKsifNtpjWqhfOdUmV/rzI6ZnVhTqHaZpFHcxJANZRSZ1pdJ9Iuw9yL4eRHZMXlD5+IGi7tuHZlARtOVCuywH8L2U/XNodtzC1l09FmT8A7HYyNL8IVUxlHNt6wBZ71mVMH4zyMTwu53A8R82Tr0T9xz+vpZNEfRctDW2Ffh5Afir7AOMoYfud4LTQU8YYAM4dgsVfFB4fX6ieqzPR3rwVT8+MMqGJY2OvDDF14cepfWMdC501hSGvzwPFiVdSFK8KqdxG05lr/qahW1n0D+TUIZ8oMI79JDyMKDS0OCbG1cvv3nvxPX3YusxTPvVq13mpph58PtKYFk4WYg4DMFFxXa8m7v8gXc+pkNSOVyUY5LL0tDUCukpYLVZUvIvx7gDNI7Q8ORsLyRokROirXAGN4BQSbnVnfiOsbh+meLZqvQVK8d+ALvyI+AUF+XS97zbjzibEcGYPZUFVSEGlEBtyd71H2TyFTl/z/T9FLoYAqDt3LdtldllbdL90LGOHkbI5yirIVxgLEHCSlHrA+IE1N+qKpxKh/IFp95CZ6fQxP8nrtZ7hB29pKTXY6BGVo3W0PiS8qnQhpfFblkuidFqlrDE4jxbKPqqJJ3cx816Xdcge86NbRmHxZHm/W9zO7Jr8Ha8rTFVylI=
